# Generated by Django 4.2.11 on 2026-02-19 09:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_add_admin_role"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="valid_role",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("CREATOR", "Creator"),
                    ("APPROVER", "Approver"),
                    ("VIEWER", "Viewer"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message=(
                            "Username may contain only letters, numbers, "
                            "and @/./+/-/_ characters."
                        ),
                        regex="^[\\w.@+-]+$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("role__in", ["CREATOR", "APPROVER", "VIEWER", "ADMIN"])
                ),
                name="valid_role",
            ),
        ),
    ]
