# Generated by Django for Phase 2 migration drift fix.
# Aligns migration state with AuditLog.Meta.ordering.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-occurred_at"]},
        ),
    ]
