# Generated by Django 4.2.11 on 2026-02-18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ledger_clients",
            },
        ),
        migrations.CreateModel(
            name="VendorType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ledger_vendor_types",
            },
        ),
        migrations.CreateModel(
            name="SubcontractorScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "ledger_subcontractor_scopes",
            },
        ),
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sites",
                        to="ledger.client",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_sites",
            },
        ),
        migrations.CreateModel(
            name="Vendor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vendor_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vendors",
                        to="ledger.vendortype",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_vendors",
            },
        ),
        migrations.CreateModel(
            name="Subcontractor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "effective_from",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("deactivated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_site",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assigned_subcontractors",
                        to="ledger.site",
                    ),
                ),
                (
                    "scope",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subcontractors",
                        to="ledger.subcontractorscope",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_subcontractors",
            },
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["is_active"], name="idx_client_active"),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["is_active"], name="idx_site_active"),
        ),
        migrations.AddIndex(
            model_name="site",
            index=models.Index(fields=["client"], name="idx_site_client"),
        ),
        migrations.AddIndex(
            model_name="vendortype",
            index=models.Index(fields=["is_active"], name="idx_vendor_type_active"),
        ),
        migrations.AddIndex(
            model_name="subcontractorscope",
            index=models.Index(fields=["is_active"], name="idx_scope_active"),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(fields=["vendor_type"], name="idx_vendor_type"),
        ),
        migrations.AddIndex(
            model_name="subcontractor",
            index=models.Index(fields=["scope"], name="idx_subcontractor_scope"),
        ),
        migrations.AddIndex(
            model_name="subcontractor",
            index=models.Index(
                fields=["assigned_site"], name="idx_subcontractor_site"
            ),
        ),
        migrations.AddConstraint(
            model_name="vendor",
            constraint=models.UniqueConstraint(
                fields=["name", "vendor_type"], name="unique_vendor_name_per_type"
            ),
        ),
        migrations.AddConstraint(
            model_name="subcontractor",
            constraint=models.UniqueConstraint(
                fields=["name", "scope"], name="unique_subcontractor_name_per_scope"
            ),
        ),
        migrations.AddIndex(
            model_name="vendor",
            index=models.Index(
                condition=models.Q(("is_active", True)),
                fields=["id"],
                name="idx_vendor_active",
            ),
        ),
    ]
