# Generated by Django 4.2.11 on 2026-02-15 11:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_batches",
            },
        ),
        migrations.CreateModel(
            name="PaymentRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("beneficiary_name", models.CharField(max_length=255)),
                ("beneficiary_account", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("PENDING_APPROVAL", "Pending Approval"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("PAID", "Paid"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="payments.paymentbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_requests",
            },
        ),
        migrations.CreateModel(
            name="ApprovalRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[("APPROVED", "Approved"), ("REJECTED", "Rejected")],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approval",
                        to="payments.paymentrequest",
                    ),
                ),
            ],
            options={
                "db_table": "approval_records",
            },
        ),
        migrations.CreateModel(
            name="SOAVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("document_reference", models.CharField(max_length=512)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="soa_versions",
                        to="payments.paymentrequest",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_soas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "soa_versions",
                "indexes": [
                    models.Index(fields=["payment_request"], name="idx_soa_request")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="soaversion",
            constraint=models.CheckConstraint(
                check=models.Q(("version_number__gte", 1)),
                name="version_number_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="soaversion",
            constraint=models.UniqueConstraint(
                fields=("payment_request", "version_number"),
                name="unique_request_version",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(fields=["batch"], name="idx_request_batch"),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(fields=["status"], name="idx_request_status"),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["batch", "status"], name="idx_request_batch_status"
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        [
                            "DRAFT",
                            "SUBMITTED",
                            "PENDING_APPROVAL",
                            "APPROVED",
                            "REJECTED",
                            "PAID",
                        ],
                    )
                ),
                name="valid_request_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(("amount__gt", 0)), name="amount_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(fields=["status"], name="idx_batch_status"),
        ),
        migrations.AddIndex(
            model_name="paymentbatch",
            index=models.Index(fields=["created_by"], name="idx_batch_created_by"),
        ),
        migrations.AddConstraint(
            model_name="paymentbatch",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["DRAFT", "SUBMITTED", "PROCESSING", "COMPLETED", "CANCELLED"],
                    )
                ),
                name="valid_batch_status",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentbatch",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status", "DRAFT"),
                    ("submitted_at__isnull", False),
                    _connector="OR",
                ),
                name="submitted_at_set_when_not_draft",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentbatch",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("status__in", ["DRAFT", "SUBMITTED", "PROCESSING"]),
                    ("completed_at__isnull", False),
                    _connector="OR",
                ),
                name="completed_at_set_when_closed",
            ),
        ),
        migrations.AddIndex(
            model_name="approvalrecord",
            index=models.Index(fields=["payment_request"], name="idx_approval_request"),
        ),
        migrations.AddConstraint(
            model_name="approvalrecord",
            constraint=models.CheckConstraint(
                check=models.Q(("decision__in", ["APPROVED", "REJECTED"])),
                name="valid_decision",
            ),
        ),
    ]
