# Generated by Django 4.2.11 on 2026-02-18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_soaversion_source_uploaded_by_nullable"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=255)),
                ("operation", models.CharField(max_length=100)),
                ("target_object_id", models.UUIDField(blank=True, null=True)),
                ("response_code", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "idempotency_keys",
            },
        ),
        migrations.AddIndex(
            model_name="idempotencykey",
            index=models.Index(fields=["key"], name="idx_idempotency_key"),
        ),
        migrations.AddConstraint(
            model_name="idempotencykey",
            constraint=models.UniqueConstraint(
                fields=["key", "operation"], name="unique_idempotency_per_operation"
            ),
        ),
    ]
