# Generated by Django 4.2.11 on 2026-02-18

from django.db import migrations, models
import django.core.validators
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_idempotencykey"),
        ("ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="entity_type",
            field=models.CharField(
                blank=True,
                choices=[("VENDOR", "Vendor"), ("SUBCONTRACTOR", "Subcontractor")],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="vendor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_requests",
                to="ledger.vendor",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="subcontractor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_requests",
                to="ledger.subcontractor",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="site",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payment_requests",
                to="ledger.site",
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="base_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="extra_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="extra_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="total_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=15,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="vendor_snapshot_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="site_snapshot_code",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="subcontractor_snapshot_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="version",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="paymentrequest",
            name="execution_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["status", "batch"], name="idx_request_status_batch"
            ),
        ),
    ]
