# Generated by Django 4.2.11 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_add_phase2_fields"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        models.Q(("entity_type__isnull", True))
                        & models.Q(("beneficiary_name__isnull", False))
                    )
                    | (
                        models.Q(("entity_type__isnull", False))
                        & models.Q(("beneficiary_name__isnull", True))
                    )
                ),
                name="legacy_or_ledger_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        models.Q(("vendor_id__isnull", False))
                        & models.Q(("subcontractor_id__isnull", True))
                    )
                    | (
                        models.Q(("vendor_id__isnull", True))
                        & models.Q(("subcontractor_id__isnull", False))
                    )
                    | (
                        models.Q(("vendor_id__isnull", True))
                        & models.Q(("subcontractor_id__isnull", True))
                    )
                ),
                name="vendor_or_subcontractor_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="paymentrequest",
            constraint=models.CheckConstraint(
                check=models.Q(("total_amount__isnull", True))
                | models.Q(
                    ("total_amount", models.F("base_amount") + models.F("extra_amount"))
                ),
                name="total_amount_integrity",
            ),
        ),
    ]
