# Generated by Django 4.2.11 on 2026-02-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0006_ledger_nullable_legacy_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idempotencykey",
            name="response_code",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="idempotencykey",
            name="target_object_id",
            field=models.UUIDField(null=True),
        ),
        migrations.AddIndex(
            model_name="paymentrequest",
            index=models.Index(
                fields=["execution_id"], name="idx_request_execution_id"
            ),
        ),
    ]
