# Generated by Django 4.2.11 on 2026-02-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_alter_idempotencykey_response_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrequest",
            name="execution_id",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
